* Plover: Logiciel de sténotypie Open Source

Plover est un projet de logiciel informatique open source impulsé aux
États-Unis par Mirabai Knight, sténotypiste, Joshua Harlan Lifton et
Hesky Fisher, programmeurs informatiques.

Plover permet d'utiliser un clavier d'ordinateur pour
effectuer les accords nécessaires à cette méthode de saisie.

Cependant, les claviers d'ordinateurs traditionnels ne sont
compatibles que de manière partielle.

Un clavier offrant la technologie n-key rollover est nécessaire pour
faire fonctionner Plover de manière optimale, le plus accessible
étant le ~Microsoft SideWinder X4~.

Plover supporte également un certain nombre de modèles de machines de
sténotypie produites aux États-Unis :

- Gemini PR (alias Gemini Enhanced)
- TX Bolt (alias Gemini TX)
- Stentura
- Treal
- Passport

Plover-France est une tentative pour faire fonctionner Plover avec un
clavier de sténotypie français sur le modèle Grandjean dont la
disposition schématique est la suivante :

| S | P | T | * | N |   | O | A | I | n | D |
| K | M | F | R | L | Y | E | U | l | $ | C |

Le projet Plover original ne prend en charge, pour l'instant, que la
disposition dite de Ward Stone Ireland.

Le fichier d'information original du projet, en anglais, est dénommé
[[https://github.com/azizyemloul/plover-france/blob/master/_README.rst][_README.rst]].


Wiki http://stenoknight.com/wiki/Main_Page

Forum http://stenoknight.com/plover/aviary/phpBB3/

Blog http://plover.stenoknight.com/

Liste de discussion https://groups.google.com/forum/#!forum/ploversteno


#  LocalWords:  Plover Mirabai Knight Joshua Harlan Lifton Hesky PR
#  LocalWords:  Fisher n-key rollover README.rst Stentura Gemini TX
#  LocalWords:  Enhanced Bolt Treal Passport Plover-France Grandjean
