#+BEGIN_EXAMPLE
  ___                                           ___
 | S |___                                   ___| D |
 |___| P |___                           ___| ᴎ |___|
 | K |___| T |___                   ___| I |___| C |
 |___| M |___| * |___     _     ___| A |___| $ |___|
     |___| F |___| N |   / \   | O |___| Ł |___|
         |___| R |___|  /   \  |___| U |___|
             |___| L | /  Y  \ | E |___|
                 |___||       ||___|
                       \_____/
#+END_EXAMPLE

#+BEGIN_EXAMPLE
 _____ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ ___ _____
|TAB  | S | P | T | * | L |   | O | A | I | ᴎ | D |   |Enter|
|_____|___|___|___|___|___|___|___|___|___|___|___|___|     |
|MAJ   |K  |M  |F  |R  |L  |Y  |E  |U  |Ł  |$  |C  |   |  ⏎ |
|______|___|___|___|___|___|___|___|___|___|___|___|___|____|
| ⇧  |   |   |   |   |  L|  Y|  E|   |   |   |   |⇧         |
|____|___|___|___|___|___|___|___|___|___|___|___|__________|
#+END_EXAMPLE


*** Plover: Logiciel libre de sténotypie
Plover est un projet informatique libre impulsé aux États-Unis par la
sténotypiste *Mirabai Knight* et les programmeurs informatiques
*Joshua Harlan Lifton* et *Hesky Fisher*.

Plover permet d'utiliser un clavier d'ordinateur pour
effectuer les accords nécessaires à cette méthode de saisie.

Cependant, les claviers d'ordinateurs traditionnels ne sont
compatibles que de manière partielle.

Un clavier offrant la technologie n-key rollover est nécessaire pour
faire fonctionner Plover de manière optimale, le plus accessible
étant le ~Microsoft SideWinder X4~.

Plover supporte également un certain nombre de protocoles de machines de
sténotypie produites aux États-Unis :
- Gemini PR (alias Gemini Enhanced)
- TX Bolt (alias Gemini TX)
- Stentura
- Treal
- Passport
*** Plover-France :
Plover-France est une tentative pour faire fonctionner Plover avec un
clavier de sténotypie français - dit Grandjean, du nom de son
concepteur - dont la disposition schématique est la suivante :

|  S  |  P  |  T  |  *  |  N  |     |  O  |  A  |  I  |  ᴎ  |  D  |
|  K  |  M  |  F  |  R  |  L  |  Y  |  E  |  U  |  Ł  |  $  |  C  |
|     |     |     |     | *L* | *Y* | *E* |     |     |     |     |

Le projet Plover original ne prend en charge, pour l'instant, que la
disposition dite de ~Ward Stone Ireland~, schématisée dans le tableau
suivant :

| S | T | P | H | * |   | F | P | L | T | D |
| S | K | W | R | * |   | R | B | G | S | Z |
|   |   |   | A | O |   | E | U |   |   |   |


Le fichier d'information original du projet, en anglais, est dénommé
[[https://github.com/azizyemloul/plover-france/blob/master/_README.rst][_README.rst]].

Veuillez vous y rapportez pour plus d'informations, ainsi qu'aux sites
suivants, en anglais :
- Le wiki http://stenoknight.com/wiki/Main_Page
- Le forum http://stenoknight.com/plover/aviary/phpBB3/
- Le blog http://plover.stenoknight.com/
- La liste de discussion https://groups.google.com/forum/#!forum/ploversteno

#  LocalWords:  Plover Mirabai Knight Joshua Harlan Lifton Hesky PR
#  LocalWords:  Fisher n-key rollover README.rst Stentura Gemini TX
#  LocalWords:  Enhanced Bolt Treal Passport Plover-France Grandjean
#  LocalWords:  blog wiki orthography.py steno.py LocalWords
*** Historique des interventions sur le code original
- Ajout d'un clavier français <2013-11-22 ven.>
- Changement de ~steno.py~, coeur du logiciel pour accepter les accords en français. <2013-11-22 ven.>
- Changements expérimentaux sur orthography.py. <2013-11-28 jeu.>.
*** TODO Reste à faire :
- Améliorer orthography.py pour prendre en charge les règles orthographiques françaises.
- Mettre en place le dictionnaire
- Étudier les suffixes et les préfixes dans le dictionnaire.
